// AUTO-GENERATED by scripts/gen-pickups.mjs — do not edit by hand.
// Distinct car pickup locations + car counts, for the rental search autocomplete.
export type Pickup = { name: string; count: number };

export const PICKUPS: Pickup[] = [
  {"name":"Izmir Adnan Menderes","count":17},
  {"name":"Antalya","count":15},
  {"name":"Adiyaman","count":12},
  {"name":"Hatay Antakya","count":11},
  {"name":"Antalya Alanya Gazipasa","count":10},
  {"name":"İstanbul Sabiha Gökçen Havalimanı","count":7},
  {"name":"Agri Ahmed I Hani Havaalani","count":5},
];
