/**
 * Generates supabase/seed.sql — schema (from 0001_init.sql) + real demo data
 * (8 Kıbrıs hotels with rooms/reviews + a 7-car fleet). Idempotent: safe to
 * re-run in the Supabase SQL editor. Content from docs/research/CONTENT.md and
 * public/images/hotels. Run: node scripts/gen-seed.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schema = readFileSync(join(root, "supabase/migrations/0001_init.sql"), "utf8");

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const j = (v) => "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";
const img = (n) => `/images/hotels/${n}.webp`;
const r2 = (n) => Math.round(n);

const ALL = ["concorde-luxury","merit-park","grand-pasha-kyrenia","salamis-bay","vuni-palace","acapulco","pia-bella","riverside-garden"];
const gallery = (own) => [own, ...ALL.filter((n) => n !== own)].slice(0, 4).map(img);

const AMENITIES = ["Özel Plaj","Açık Havuz","Kapalı Havuz","Spa & Wellness","Fitness","Ücretsiz Otopark","Ücretsiz Wi-Fi","Restoran"];
const POIS = [
  { type: "airport", name: "Ercan Havalimanı", distance: "42 km" },
  { type: "beach", name: "Özel Plaj", distance: "0 m" },
  { type: "center", name: "Şehir Merkezi", distance: "3.2 km" },
  { type: "landmark", name: "Girne Limanı", distance: "5.5 km" },
];
const CAT = [
  { label: "Temizlik", score: 9.1 },
  { label: "Konum", score: 8.8 },
  { label: "Hizmet", score: 9.0 },
  { label: "Konfor", score: 8.7 },
  { label: "Fiyat/Performans", score: 8.4 },
];
const LIKES = [
  "Misafirler temiz ve ferah odalardan övgüyle bahsediyor",
  "Deniz manzarası ve özel plaj çok beğeniliyor",
  "Personelin ilgisi sık sık öne çıkarılıyor",
  "Zengin açık büfe kahvaltı misafirlerin favorisi",
];

const HOTELS = [
  ["merit-park","Merit Park Hotel & Casino","Karaoğlanoğlu","Girne",9.7,"Olağanüstü","Ultra Her Şey Dahil",56000,"merit-park",35.356,33.2705,1840],
  ["concorde-luxury-resort","Concorde Luxury Resort","Bafra","Gazimağusa",9.3,"Mükemmel","Ultra Her Şey Dahil",56160,"concorde-luxury",35.401,34.002,2103],
  ["salamis-bay-conti","Salamis Bay Conti Resort Hotel","Yeniboğaziçi","Gazimağusa",8.9,"Harika","Ultra Her Şey Dahil",33000,"salamis-bay",35.1235,33.942,1567],
  ["pia-bella","Pia Bella Hotel","Yukarı Girne","Girne",8.6,"Harika","Kahvaltı Dahil",16562,"pia-bella",35.3348,33.3225,921],
  ["vuni-palace","Vuni Palace Hotel","Karakum","Girne",8.5,"Harika","Yarım Pansiyon",30865,"vuni-palace",35.3415,33.3055,1342],
  ["grand-pasha-kyrenia","Grand Pasha Kyrenia Hotel & Spa","Yukarı Girne","Girne",8.4,"Çok İyi","Sadece Oda",15232,"grand-pasha-kyrenia",35.336,33.319,688],
  ["acapulco","Acapulco Resort Convention & Spa","Çatalköy","Girne",7.9,"İyi","Yarım Pansiyon",32400,"acapulco",35.3705,33.364,1198],
  ["riverside-garden","Riverside Garden Resort","Yayla","Girne",7.3,"İyi","Sadece Oda",8658,"riverside-garden",35.33,33.251,534],
];

const ROOM_DEFS = [
  ["Standart Oda", 28, ["Klima","Ücretsiz Wi-Fi","Minibar","LCD TV"], 1.0, true],
  ["Deluxe Deniz Manzaralı Oda", 36, ["Deniz Manzarası","Klima","Balkon","Ücretsiz Wi-Fi","Minibar"], 1.18, true],
  ["Aile Suiti", 52, ["2 Yatak Odası","Oturma Alanı","Deniz Manzarası","Klima","Minibar"], 1.45, false],
];

const REVIEWS = (name, rating) => [
  ["AY","Ahmet Y.","Mayıs 2026",rating,`${name} konaklamamız harikaydı. Personel çok ilgili, odalar tertemizdi. Kesinlikle tekrar geleceğiz.`,"Deluxe Oda","3 gece · Mayıs 2026","Çift"],
  ["SK","Selin K.","Nisan 2026",Math.max(0,rating-0.4),"Konumu ve manzarası muhteşem. Kahvaltı çeşitleri bol. Havuz biraz kalabalıktı ama genel olarak memnun kaldık.","Standart Oda","2 gece · Nisan 2026","Aile"],
  ["MD","Murat D.","Nisan 2026",Math.min(10,rating+0.2),"Fiyat/performans açısından çok başarılı. Deniz temiz, plaj düzenli. Animasyon ekibi keyifliydi.","Aile Odası","4 gece · Nisan 2026","Aile"],
];

const CARS = [
  ["renault-clio","Renault Clio","Manuel","Benzin","Ekonomik","Bookera",1090,8.6,412,21,"#0a7c8a"],
  ["fiat-egea-manuel","Fiat Egea","Manuel","Dizel","Ekonomik","Goldcar",1190,8.4,587,21,"#e8552d"],
  ["hyundai-i20","Hyundai i20","Otomatik","Benzin","Ekonomik","Europcar",1450,8.8,333,21,"#1b9e3e"],
  ["fiat-egea-otomatik","Fiat Egea","Otomatik","Dizel","Orta","Bookera",1620,8.7,744,23,"#0a7c8a"],
  ["toyota-corolla","Toyota Corolla","Otomatik","Hibrit","Orta","Praticar",1980,9.1,256,25,"#b8262b"],
  ["peugeot-2008","Peugeot 2008","Otomatik","Dizel","SUV","Europcar",2350,8.9,198,25,"#1b9e3e"],
  ["mercedes-c200","Mercedes-Benz C200","Otomatik","Benzin","Lüks","Goldcar",4200,9.3,121,27,"#e8552d"],
];

let out = "-- AUTO-GENERATED by scripts/gen-seed.mjs — schema + demo data.\n";
out += "-- Paste this whole file into the Supabase SQL editor and Run.\n\n";
out += schema + "\n\n";
out += "-- ───────────────────────── seed data (idempotent) ─────────────────────────\nbegin;\n";
out += "delete from public.reviews where hotel_id between 1 and 8;\n";
out += "delete from public.rooms   where hotel_id between 1 and 8;\n";
out += "delete from public.hotels  where id between 1 and 8;\n\n";

HOTELS.forEach((h, i) => {
  const [slug,name,district,city,rating,label,board,price,image,lat,lng,reviews] = h;
  const id = i + 1;
  const disc = 20;
  const old = r2(price / 0.8);
  const desc = `${name}, ${city} bölgesinde ${district} mevkiinde yer alan ${label.toLowerCase()} puanlı bir tatil tesisidir. Özel plajı, açık ve kapalı havuzları, spa merkezi ve zengin yeme-içme seçenekleriyle konforlu bir konaklama sunar.`;
  out += `insert into public.hotels (id,slug,name,city,district,region,region_slug,location,rating,rating_label,star_rating,review_count,board,description,lat,lng,total_photos,gallery,amenities,pois,category_scores,ai_likes,discount_pct,old_price_tl,price_tl,nights,rooms_left,is_cyprus,is_domestic) values (`;
  out += `${id},${q(slug)},${q(name)},${q(city)},${q(district)},'Kıbrıs','kibris-45',${q(`${district}, ${city}, Kıbrıs`)},${rating},${q(label)},5,${reviews},${q(board)},${q(desc)},${lat},${lng},24,${j(gallery(image))},${j(AMENITIES)},${j(POIS)},${j(CAT)},${j(LIKES)},${disc},${old},${price},2,3,true,false);\n`;
});
out += "\n";

HOTELS.forEach((h, i) => {
  const [, , , , , , , price] = h;
  const id = i + 1;
  ROOM_DEFS.forEach(([rname, size, am, mult, canc], si) => {
    const p = r2(price * mult);
    const old = r2(p / 0.8);
    out += `insert into public.rooms (hotel_id,name,size_m2,amenities,images,board,cancellable,discount_pct,old_price_tl,price_tl,sort_order) values (`;
    out += `${id},${q(rname)},${size},${j(am)},${j(gallery(h[8]).slice(0, 3))},${q(h[6])},${canc},20,${old},${p},${si});\n`;
  });
});
out += "\n";

HOTELS.forEach((h, i) => {
  const id = i + 1;
  REVIEWS(h[1], h[4]).forEach((rv, ri) => {
    const [initials,rname,date,rating,text,room,stay,gtype] = rv;
    out += `insert into public.reviews (hotel_id,initials,name,review_date,rating,text,room,stay,guest_type,source_key) values (`;
    out += `${id},${q(initials)},${q(rname)},${q(date)},${rating},${q(text)},${q(room)},${q(stay)},${q(gtype)},${q(`seed-${id}-${ri}`)});\n`;
  });
});
out += "\n";

out += `delete from public.cars where slug in (${CARS.map((c) => q(c[0])).join(",")});\n`;
CARS.forEach((c) => {
  const [slug,name,trans,fuel,cls,supplier,daily,rating,reviews,minAge,accent] = c;
  out += `insert into public.cars (slug,name,transmission,fuel,min_age,km_limit,deposit_tl,delivery,car_class,supplier,rating,review_count,location,daily_tl,total_tl,free_cancel,accent) values (`;
  out += `${q(slug)},${q(name)},${q(trans)},${q(fuel)},${minAge},300,7500,'Havalimanı Ofis',${q(cls)},${q(supplier)},${rating},${reviews},'İstanbul Sabiha Gökçen Havalimanı',${daily},${daily * 3},true,${q(accent)});\n`;
});
out += "\ncommit;\n";

writeFileSync(join(root, "supabase/seed.sql"), out, "utf8");
console.log("Wrote supabase/seed.sql (" + out.length + " bytes)");
