// Builds the car pickup-location autocomplete index from the live catalogue:
// distinct cars.location + counts → src/lib/pickups.data.ts. Read-only (anon).
import { createClient } from "@supabase/supabase-js";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

try {
  const raw = readFileSync(".env.local", "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
} catch {}

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  { auth: { persistSession: false } },
);

const { data, error } = await sb.from("cars").select("location").limit(1000);
if (error) { console.error(error); process.exit(1); }

const counts = new Map();
for (const r of data) {
  const name = (r.location ?? "").trim();
  if (name) counts.set(name, (counts.get(name) ?? 0) + 1);
}

const list = [...counts.entries()]
  .map(([name, count]) => ({ name, count }))
  .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, "tr"));

const out =
  "// AUTO-GENERATED by scripts/gen-pickups.mjs — do not edit by hand.\n" +
  "// Distinct car pickup locations + car counts, for the rental search autocomplete.\n" +
  "export type Pickup = { name: string; count: number };\n\n" +
  "export const PICKUPS: Pickup[] = " +
  JSON.stringify(list, null, 0).replace(/},/g, "},\n  ").replace(/^\[/, "[\n  ").replace(/\]$/, ",\n]") +
  ";\n";

writeFileSync(path.join("src", "lib", "pickups.data.ts"), out, "utf8");
console.log(`✓ wrote ${list.length} pickups → src/lib/pickups.data.ts`);
console.log(list.map((p) => `${p.name}(${p.count})`).join(", "));
